version: "3.9"

services:
  broker:
    build: ./broker
    container_name: broker
    ports:
      - "5554:5554"
      - "5555:5555"

  server-python:
    build: ./server-python
    container_name: server-python
    environment:
      BROKER_ADDRESS: tcp://broker:5555
      PUBSUB_ADDRESS: tcp://pubsub-proxy:5557
      REFERENCE_ADDRESS: tcp://reference-service:5560
      SERVER_NAME: server-python
      SERVER_DB_PATH: data/server.db
    volumes:
      - ./server-python/data:/app/data
    depends_on:
      - broker
      - pubsub-proxy
      - reference-service

  client-python:
    build: ./client-python
    container_name: client-python
    environment:
      SERVER_ADDRESS: tcp://broker:5554
      PUBSUB_PROXY_ADDRESS: tcp://pubsub-proxy:5558
      BOT_USERNAME: bot_python_1
      BOT_CHANNEL: geral
    depends_on:
      - broker
      - server-python 

  pubsub-proxy:
    build: ./pubsub-proxy
    container_name: pubsub-proxy
    ports:
      - "5557:5557"
      - "5558:5558"

  reference-service:
    build: ./reference-service
    container_name: reference-service
    ports:
      - "5560:5560"
  
  server-java:
    build: ./server-java
    container_name: server-java
    environment:
      BROKER_ADDRESS: tcp://broker:5555
      PUBSUB_ADDRESS: tcp://pubsub-proxy:5557
      REFERENCE_ADDRESS: tcp://reference-service:5560
      SERVER_NAME: server-java
      SERVER_DB_PATH: data/server-java.db
    volumes:
      - ./server-java/data:/app/data
    depends_on:
      - broker
      - pubsub-proxy
      - reference-service

  client-java:
    build: ./client-java
    container_name: client-java
    environment:
      SERVER_ADDRESS: tcp://broker:5554
      PUBSUB_PROXY_ADDRESS: tcp://pubsub-proxy:5558
      BOT_USERNAME: bot_java_1
      BOT_CHANNEL: geral
    depends_on:
      - broker
      - pubsub-proxy
      - server-java