version: "3.9"

services:
  broker:
    build: ./broker
    container_name: broker
    ports:
      - "5554:5554"
      - "5555:5555"

  server-python:
    build: ./server-python
    container_name: server-python
    environment:
      BROKER_ADDRESS: tcp://broker:5555
      SERVER_DB_PATH: data/server.db
    volumes:
      - ./server-python/data:/app/data
    depends_on:
      - broker

  client-python:
    build: ./client-python
    container_name: client-python
    environment:
      SERVER_ADDRESS: tcp://broker:5554
      BOT_USERNAME: bot_python_1
      BOT_CHANNEL: geral
    depends_on:
      - broker
      - server-python 