def print_message(direction: str, msg) -> None:
    print("=" * 60)
    print(f"[{direction}]")
    print(f"type          : {msg.type}")
    print(f"timestamp     : {msg.timestamp}")
    print(f"logical_clock : {msg.logical_clock}")
    print(f"request_id    : {msg.request_id}")
    print(f"username      : {msg.username}")
    print(f"channel_name  : {msg.channel_name}")
    print(f"message_text  : {msg.message_text}")
    print(f"server_name   : {msg.server_name}")
    print(f"server_rank   : {msg.server_rank}")
    print(f"physical_time : {msg.physical_time}")
    print(f"success       : {msg.success}")
    print(f"error_message : {msg.error_message}")
    print(f"channels      : {list(msg.channels)}")
    print(f"servers       : {list(msg.servers)}")
    print("=" * 60)